apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: devops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:

      # ✅ INIT CONTAINER
      initContainers:
        - name: init-db
          image: postgres:15-alpine
          command:
            - sh
            - -c
            - |
              echo "⏳ Waiting for Postgres..."
              until pg_isready -h postgres-service -U user; do
                sleep 2
              done

              echo "🚀 Creating DB if not exists..."
              psql -h postgres-service -U user -tc "SELECT 1 FROM pg_database WHERE datname = 'devopsdb'" | grep -q 1 || \
              psql -h postgres-service -U user -c "CREATE DATABASE devopsdb;"

          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: POSTGRES_PASSWORD
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: db-secret
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-storage

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc